apiVersion: v1
kind: Service
metadata:
  name: mstrackertaskback-serv
spec:
  selector:
    app: gestortrackertaskback
  ports:
  - port: 5052
    targetPort: 5052
  type: LoadBalancer
  externalIPs:
    - 192.168.5.70